### ISSUE TITLE
Sbt test failing giving null pointer exception.

### ISSUE THREAD

**Issue by ankur-1989** [sukyoung/safe#27]
I set the SAFE_HOME and then ran sbt compile. sbt compile ran successfully but when I ran sbt test, it failed. It is giving null pointer exception at line number 226 in CoreTest.scala and even after setting the $SAFE_HOME/bin in bashrc it does not recognize safe command. Even i tried to run directly inside bin directory. 
Could you please help me?

**Comment by jhnaldo** [comment]
Hello,

Sorry for the late response.
Can you show the detailed error message?
I think that it is helpful to check which parts are problems.

**Comment by ankur-1989** [comment]
Hi @jhnaldo , 
I am getting following issues while running sbt test command.
[info] Loading project definition from *******/safe/project
[info] Set current project to SAFE (in build file:*******/safe/)
*******/safe/bin/checkCopyrights.sh: 14: cd: can't cd to /*******/safe
*******/safe/bin/checkCopyrights.sh: 24: cd: can't cd to *******/safe/src
find: ‘../timestamp’: No such file or directory
find: ‘../timestamp’: No such file or directory
find: ‘../timestamp’: No such file or directory
*******/safe/bin/checkCopyrights.sh: 24: cd: can't cd to *******/safe/tests
find: ‘../timestamp’: No such file or directory
find: ‘../timestamp’: No such file or directory
find: ‘../timestamp’: No such file or directory
[Ljava.io.File;@2073630f
[Ljava.lang.String;@2843c496
[info] Run completed in 6 seconds, 184 milliseconds.
[info] Total number of tests run: 612
[info] Suites: completed 0, aborted 1
[info] Tests: succeeded 0, failed 612, canceled 0, ignored 0, pending 0
[info] *** 1 SUITE ABORTED ***
[info] *** 612 TESTS FAILED ***
[error] Error during tests:
[error] 	kr.ac.kaist.safe.CoreTest
[error] (test:testOnly) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 9 s, completed Mar 22, 2019 10:07:17 AM

Thanks and Regards,
Ankur

**Comment by jhnaldo** [comment]
I have several questions.
1. What is the owner or permission of the safe directory?
    I think the wrong owner or permission could be a possible reason of the error.

2. Did you delete your "timestamp" file? or is your version is not recent?
    In the original version, the "timestamp" file should exist in the safe directory.

3. Can you run "bin/safe" shell script?
    If the "sbt compile" succeeded, you can run the following command and
    it should show the following message:

```
$ bin/safe help

Invoked as script: safe args
Invoked by java: java ... kr.ac.kaist.safe.Safe args

* command list:
    Each command consists of following phases.
    format: {command} {phase} [>> {phase}]*

    parse          parser
    astRewrite     parser >> astRewriter
    compile        parser >> astRewriter >> compiler
    ...

```

**Comment by jhnaldo** [comment]
Hi @ankur-1989 ,
I reproduced your error in my environment.
I think that your $SAFE_HOME setting is not correct.
Your $SAFE_HOME should point to the directory of the our safe directory.
Please check it.

**Comment by ankur-1989** [comment]
Yes you are right. Thanks a lot for taking out your time.
