### ISSUE TITLE
document.getElementById is not implemented

### ISSUE THREAD

**Issue by auppar** [sukyoung/safe#28]
I tried to analyse the html file given that the tool analyses DOM interactions in the HTML page. But when i run the commond

$safe bugDetect {respective html file}

I see a message saying that getElementById is not implemented. On checking the repository i don't find relevant files relating DOM modeller or Event modeller as mentioned in the SAFE paper.

**Comment by jhnaldo** [comment]
Dear auppar,

We does not provide actual implementation of the modeling for "getElementById" function.
If you want to analyze this function, you should implement its modeling in the file "src/main/resources/jsModels/built_in/Element.jsmodel".
