### ISSUE TITLE
User Manual not found

### ISSUE THREAD

**Issue by aliahsan07** [sukyoung/safe#33]
On clicking the link for user manual from the repo readme it displays a 404 GitHub page.

**Comment by aliahsan07** [comment]
The said link is: https://github.com/kaist-plrg/safe/blob/master/doc/manual.pdf
The working link (works on concolic branch) is: https://github.com/sukyoung/safe/blob/master/doc/manual.pdf

**Comment by jhnaldo** [comment]
Thank you for pointing out the wrong links in the README file.
I fixed errors you mentioned: https://github.com/sukyoung/safe/commit/5814bf82309fe05bc44fa82d8e23965150d9b766
