### ISSUE TITLE
sbt compile is failing 

### ISSUE THREAD

**Issue by aliahsan07** [sukyoung/safe#34]
sbt compile is failing on a linux machine with the error:

`[error] (compile:buildParsers) Error opening http://central.maven.org/maven2/xtc/rats/2.4.0/rats-2.4.0.jar: java.io.IOException: Server returned HTTP response code: 501 for URL: http://central.maven.org/maven2/xtc/rats/2.4.0/rats-2.4.0.jar`

**Comment by jhnaldo** [comment]
Thank you for your kind notification for wrong URL of xtc/rats.
We accepted your pull request https://github.com/sukyoung/safe/pull/35 and merged into our repository.
