### ISSUE TITLE
Sharing between arguments object and parameters

### ISSUE THREAD

**Issue by happibum** [sukyoung/safe#4]
```javascript
function f(a) {
    arguments[0] = "changed";
    return a;
}

function g(a) {
    a = "changed";
    return arguments[0];
}

var ret1 = f('given');
var ret2 = g('given');
```
For chrome, firefox and IE, ret1 == ret2 == 'changed'.
However, SAFE analyzer says that ret1 == ret2 == 'given' at the end of the program.

**Comment by sukyoung** [comment]
As we stated in Chapter 4 of [our document](https://github.com/sukyoung/safe/tree/master/doc/manual), SAFE currently supports only such cases where `arguments` and actual arguments do not change in function bodies.
